# Generated by Django 4.0.4 on 2022-05-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_room_current_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
